build_task:
  container:
    matrix:
      image: nvidia/cuda:11.0-devel-ubuntu18.04-rc
    cpu: 8
    memory: 24


  depdendencies_script:
    - apt-get update
    - apt-get install build-essential \
      git-core wget make cmake gcc-multilib libgtest-dev libboost-all-dev \
      libarmadillo-dev libopenblas-dev libfftw3-dev liblapack-dev liblapacke-dev \
      libxml2-dev libxslt-dev libpugixml-dev libhdf5-dev libplplot-dev libdcmtk-dev \
      python3-dev python3-pip python3-h5py python3-scipy python3-pyxb ninja-build
  mtime_script:
    - apt-get update
    - apt-get install ruby-full -y
    - gem install mtime_cache


  ismrmrd_cache:
    folder: /opt/code/ismrmrd
    populate_script:
      - cd /opt/code
      - git clone https://github.com/ismrmrd/ismrmrd.git
      - cd ismrmrd
      - mkdir build
      - cd build
      - cmake ..
      - make -j8
    fingerprint_script:
      - git ls-remote https://github.com/ismrmrd/ismrmrd.git  | grep HEAD | awk '{ print $1}'

  install_ismrmrmd_script:
    - cd /opt/code/ismrmrd/build
    - mtime_cache ../**/*.{%{cpp}} -c .mtime_cache/cache.json
    - make install


  ismrmrd_python_script:
    - pip3 install  git+https://github.com/ismrmrd/ismrmrd-python.git
    - pip3 install  git+https://github.com/ismrmrd/ismrmrd-python-tools.git

  make_build_cache:
    folder: build
    fingerprint_script:
      - echo "ninja $(git branch | grep \* | cut -d ' ' -f2)"
    populate_script:
    - mkdir build

  make_script:
    - cd build
    - cmake .. -G Ninja
    - mtime_cache ../**/*.{%{cpp}} -c .mtime_cache/cache.json
    - ninja
    - ninja install
    - cd /usr/local/share/gadgetron/config



